steps:
  - key: "build"
    label: ":hammer_and_wrench: Build"
    command: sleep 3600
    artifact_paths: "*.deb"

  - label: ":ubuntu: Publish"
    depends_on: "build"
    plugins:
      - publish-to-packages#v2.1.0:
          artifacts: "*.deb"
          registry: "steve-playground/oidc-example"
